version: 0.2 
   
phases:     
  install:
    runtime-versions: 
      java: openjdk8  
    commands: 
      - echo Nothing to do in the install phase...
  pre_build: 
    commands: 
      - echo Nothing to do in the pre_build phase... 
  build: 
    commands: 
      - echo Build started on `date` 
      - cd openmrs-core/ && mvn clean install -Dmaven.test.skip=true && cd -
      - cd openmrs-module-legacyui/ && mvn clean install -Dmaven.test.skip=true && cd -
  post_build: 
    commands: 
      - echo Build completed on `date` 
artifacts: 
  files: 
    - 'openmrs-core/webapp/target/openmrs.war'
    - 'openmrs-module-legacyui/omod/target/legacyui-1.6.0-SNAPSHOT.omod'     
    - 'scripts/init.sh' 
    - 'appspec.yml'
    - 'scripts/restart.sh'
 